const KEYBOARD_DISMISS_MODE_NONE = 'none';
const KEYBOARD_DISMISS_MODE_ON_DRAG = 'on-drag';

const PAGINATION_DIRECTION_HORIZONTAL = 'x';
const PAGINATION_DIRECTION_VERTICAL = 'y';

const DRAGGING_STATE_IDLE = 'idle';
const DRAGGING_STATE_DRAGGING = 'dragging';
const DRAGGING_STATE_SETTLING = 'setting';

export {
    KEYBOARD_DISMISS_MODE_NONE,
    KEYBOARD_DISMISS_MODE_ON_DRAG,
    PAGINATION_DIRECTION_HORIZONTAL,
    PAGINATION_DIRECTION_VERTICAL,
    DRAGGING_STATE_IDLE,
    DRAGGING_STATE_DRAGGING,
    DRAGGING_STATE_SETTLING
};
